### ISSUE TITLE
ACPI Error with some PXSXs.

### ISSUE THREAD

**Issue by Mindarlynn** [13thdemarch/b660m-aorus-pro-hackintosh#1]
Hi. I'm trying monterey 12.5 to my system, but i could not watch even installation page.
Can you help my case?

I have very similar system to yours,

CPU : i5-12600k
M/B: Aorus B660M Pro DDR4
Mem: G.Skill Trident 16GB * 2
SSD: SN750 * 2, Sandisk Blue SATA SSD * 1
Bios Version: F6a

log in screen (w/ -v option), It says 

ACPI Error: [_SB_.PC00.RP02.PXSX] Namespace lookup failure, AE_NOT_FOUND (20160930/dswload2-274)

No Local Variables are initialized for method [PXSX]

No Arguments are initialized for method [PXSX]

ACPI Exception: AE_NOT_FOUND, During name lookup/catalog (20160930/psobject-310)
ACPI Error: Method parse/execution failed [\_SB.PC00.RP01.PXSX] (Node ffffff0b63ef61b0), AE_NOT_FOUND (20160930/psparse-632)
ACPI Error: [_SB_PC00.RP06.PXSX] Namespace Lookup failure, AE_NOT_FOUND (20160930/dswload2-274)

No Local Variables are initialized for method [PXSX]

No Arguments are initialized for method [PXSX]

ACPI Exception: AE_NOT_FOUND, During name lookup/catalog (20160930/psobject-310)
ACPI Error: Method parse/execution failed [\_SB.PC00.RP05.PXSX] (Node ffffff0b63ef23c0), AE_NOT_FOUND (20160930/psparse-632)
ACPI Error: [_SB_PC00.RP10.PXSX] Namespace Lookup failure, AE_NOT_FOUND (20160930/dswload2-274)

after last ACPI Error is printed, my PC stucks. 
I googled this error but i couldn't get answer. Did you faced this error or similar error while installing macOS?

And in Readme.md, you wrote your M/B's bios version is F20a, but in gigabyte hompage, there is F6a for latest bios. 
Is F20a really your bios version? If it is true, can you share me F20a bios for Aorus B660M Pro DDR4?

**Comment by 13thdemarch** [comment]
Oh sorry my bad. The lastest bios version is F6a. Thank you for telling me.
You can use my EFI for i5 CPU. The ACPI is very universal, so just generate new SMBIOS data with iMacPro1,1 and install. No need to create your own CPUFriendDataProvider.kext.
Cheer.

**Comment by Mindarlynn** [comment]
Unfortunately I failed to launch 12.5 installer to my desktop even applied your EFI. If 12.4 also fails to install, I will use my macbook with clamshell mode.
Thank you for reply

**Comment by 13thdemarch** [comment]
I think you should check the BIOS setting and configure it if necessary. I haven't detail them in my repo yet because I have configured a lot of things and forgot what they are... But there are some essential settings such as CFG-Lock, ResizeBAR,... I think you should check your BIOS.

**Comment by Mindarlynn** [comment]
I think I did not understand what ResizeBAR is. When I enabled 4G Decoding, finally I can enable ResizeBAR and installer poped up. Thank you for your advise.

**Comment by 13thdemarch** [comment]
It is necessary for Navi23 graphic card.
But wait, I've just realized that your spec doesn't have graphic card, does it?

**Comment by Mindarlynn** [comment]
Oh I forgot to write my GPU. I'm using RX 570 4G graphics card. I think my gpu causes errror without ResizeBAR option.

**Comment by 13thdemarch** [comment]
Hmm... I will check everything on my system and send you another EFI folder asap.

**Comment by Mindarlynn** [comment]
Oh you dont have to do that. I'm already installing monterey. I think if there is any error with my gpu on mac, I have to try to fix it. Thank you for your kindness 
![Uploading 9BB254B0-5EA1-4858-A338-C1F13C8B3417.jpeg…]()

**Comment by 13thdemarch** [comment]
Glad to hear that. Please let me know the result, also the system stability.

**Comment by Mindarlynn** [comment]
I installed monterey 12.5 and moved opencore to disk's EFI partition.
First cpu and gpu seems work properly. I ran Cinebench, CPU score is over 16000. It is very similar to on windows. And in System Report, I can see RX 570 in Graphics/Display menu.
But, I think there is some issue about Ethernet port. I connected LAN cable between my PC and Router. But in network settings, it says like there is no cable is connected. Actually I'm using external wireless lan card, Intel AX200. So I'll use wlan until ethernet is fixed.
Your EFI works nicely! Now I'll surf internet to fix my ethernet. Thank you for share EFI and help me.

**Comment by 13thdemarch** [comment]
> I installed monterey 12.5 and moved opencore to disk's EFI partition. First cpu and gpu seems work properly. I ran Cinebench, CPU score is over 16000. It is very similar to on windows. And in System Report, I can see RX 570 in Graphics/Display menu. But, I think there is some issue about Ethernet port. I connected LAN cable between my PC and Router. But in network settings, it says like there is no cable is connected. Actually I'm using external wireless lan card, Intel AX200. So I'll use wlan until ethernet is fixed. Your EFI works nicely! Now I'll surf internet to fix my ethernet. Thank you for share EFI and help me.

Thank you very much. Glad to hear that.
But currently LAN is not worked, isn't it?

**Comment by Mindarlynn** [comment]
Unfortuately yes. Until setting my macOS, I'll use WLAN first. And when setting is done, I'll google it. Did you also show errors with ethernet like this?

**Comment by 13thdemarch** [comment]
I haven't checked the ethernet yet since I use my BCM94360CD card 😂
I will check it tomorrow.

**Comment by 13thdemarch** [comment]
@Mindarlynn 
![image](https://user-images.githubusercontent.com/59220499/185644205-224aaeda-cf56-478f-a6b6-8358936ecbcc.png)
![image](https://user-images.githubusercontent.com/59220499/185644341-90971a2c-eb20-4779-8ef2-f09105bc8802.png)
my Ethernet is fine

**Comment by Mindarlynn** [comment]
![image](https://user-images.githubusercontent.com/19931865/185646636-eb24246e-b853-45da-8e44-0d448d55a500.png)
(Enabled page is ethernet)
![image](https://user-images.githubusercontent.com/19931865/185646818-adcff396-7ab2-4075-8bfd-daa4bc4e6745.png)

Now ethernet works!
I checked my IO ports options in BIOS, I225V is gone because of crash to ISP. So I turn off my PC and Power supplier in my pc and turned on after few seconds. After this operations, I225V appears in BIOS and ethernet on mac is works!!
Thank you soooo much!!!

**Comment by 13thdemarch** [comment]
Ahaha that's great! 😂
Enjoy your hack!

**Comment by Mindarlynn** [comment]
Thank you so much!
