### ISSUE TITLE
Road to Sonoma

### ISSUE THREAD

**Issue by niypoo** [13thdemarch/b660m-aorus-pro-hackintosh#10]
How do you doing ? hope you are well.
did you upgrade to Sonoma! and if you did , there is any issues ?

**Comment by 13thdemarch** [comment]
> How do you doing ? hope you are well. did you upgrade to Sonoma! and if you did , there is any issues ?

Never better. I'm very good now. Thank you for asking. How about you?
Yes I upgraded to release version of Sonoma. Everything is ok and currently no issue with the system, except some applications which I'm using are not supported on Sonoma. I'm waiting for newer version.
I will re-write the guide for Sonoma soon when I'm free, maybe in this week.

**Comment by niypoo** [comment]
Glade to know that you are well, Thanks for your effort.
