### ISSUE TITLE
Displayport no signal

### ISSUE THREAD

**Issue by niypoo** [13thdemarch/b660m-aorus-pro-hackintosh#11]
Hello,
Hope you're doing well,

I'm facing new issue withe new monitor in Sonoma.

I have bought new monitor Asus Pa278crv and plugged with displayPort in my GPU Asus Rx 5500 tx.

windows on same pc work and mother board dose work also only in hackintosh , apple logo display then after loading finish the screen turn black and show "no signal".

Do you have any information that Can help me in that issue ?

**Comment by 13thdemarch** [comment]
black screen but it will show up after 2-3 mins.
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/Source/SSDT-BRG0.dsl
this may help but need you have to find the correct pcie address of RX 5500 on windows.
also this may help too: https://www.reddit.com/r/hackintosh/comments/hy3fu9/comment/fzagvqo/

**Comment by niypoo** [comment]
I think it's not a black screen issue the DisplayPort isn't receiving signal from card I guess because the message shows up in screen "DisplayPort has no signal"

**Comment by niypoo** [comment]
https://www.reddit.com/r/hackintosh/comments/ja4zlk/no_signal_for_a_while_before_i_see_login_screen/

That is what happened with me ,

**Comment by niypoo** [comment]
**Issue name** 
Opencore or "WhateverGreen's"  the second stage boot glitch

**issue description**
No signal for a while before I see login screen. Full specs and versions in comments.


I have fixed this issue by following this link,
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html

I will explain more what I did in my case in next photos,

<img width="2659" alt="Screenshot 2023-12-25 at 10 59 05 PM" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/13227239/e7f09c00-9eaf-41c1-91e5-0f7c7045a6c0">
<img width="2659" alt="Screenshot 2023-12-25 at 11 04 46 PM" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/13227239/72006f8d-7bdd-41ab-a78a-5beaf3b54251">

**Comment by niypoo** [comment]
I have an incomprehensible point,
after patching connect , I notice that 
sometimes I lost connect with disableport cable and connect with hdmi cable then I checked the ioregister app not recoginze the displayport at same @key , do you have any explain for that ?

<img width="1471" alt="Screenshot 2023-12-26 at 8 57 56 AM" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/13227239/579998c2-449a-4a99-9163-646c73155a6a">
<img width="1471" alt="Screenshot 2023-12-26 at 12 51 35 AM" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/13227239/537cc36f-da82-4fed-9214-88e51025b401">

**Comment by 13thdemarch** [comment]
> I have an incomprehensible point, after patching connect , I notice that sometimes I lost connect with disableport cable and connect with hdmi cable then I checked the ioregister app not recoginze the displayport at same @key , do you have any explain for that ?
> 
> <img alt="Screenshot 2023-12-26 at 8 57 56 AM" width="1471" src="https://private-user-images.githubusercontent.com/13227239/293165143-579998c2-449a-4a99-9163-646c73155a6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjQ5NjUsIm5iZiI6MTcwMzc2NDY2NSwicGF0aCI6Ii8xMzIyNzIzOS8yOTMxNjUxNDMtNTc5OTk4YzItNDQ5YS00YTk5LTkxNjMtNjQ2YzczMTU1YTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDExNTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3M2FmZTQyZDdmYWIwNzQ1YTI2Zjc4ZTQ0Y2FiMTQ4MGJjYjgwNjcyZTg1ZDliZTJmN2VmNDliODQ0NzdlZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VwS0XJNAkN65bUBX2cIslYofhjO5u8cq2BKL0l-TP24"> <img alt="Screenshot 2023-12-26 at 12 51 35 AM" width="1471" src="https://private-user-images.githubusercontent.com/13227239/293165165-537cc36f-da82-4fed-9214-88e51025b401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NjQ5NjUsIm5iZiI6MTcwMzc2NDY2NSwicGF0aCI6Ii8xMzIyNzIzOS8yOTMxNjUxNjUtNTM3Y2MzNmYtZGE4Mi00ZmVkLTkyMTQtODhlNTEwMjViNDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDExNTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZTVkN2IyOTE5MmEwMjU1ZmM1MWM2NjkyM2NkODI4NDBiMzJiOWViYzAzNjg4YzcyN2Y1ZDdlZDRhZDFiMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fsAc-PFUOJJi0MZJZBCT5t1d_G4SNRM2P0tlYAe-keY">

No, sorry. I don't.
My 6600XT currently works fine. You should remove every patches, boot-arg,... about GPU/Graphics, also my SSDT-GFX0.aml and boot again. Then find where is the issue from.

**Comment by niypoo** [comment]
I have ordered `ASUS Dual AMD Radeon RX 6600 XT OC Edition 8GB GDDR6` 🤣 I hope this card make my headache gone .

is this card like your card (@13thdemarch ) and is it fully supported with hackintosh?

**Comment by 13thdemarch** [comment]
> I have ordered `ASUS Dual AMD Radeon RX 6600 XT OC Edition 8GB GDDR6` 🤣 I hope this card make my headache gone .
> 
> is this card like your card (@13thdemarch ) and is it fully supported with hackintosh?

yes of course, fully supported. You can keep my config and install new card.
also Happy New Year man!

**Comment by niypoo** [comment]
Happy new year 🥳 🎉

**Comment by niypoo** [comment]
Greetings,
Now I have received the Rx 6600 xt and install it now I'm facing 2 issues almost 5500 xt.
by the way I'm using ProArt PA279CRV display.

and use your EFI folder with 1 changes is (disabled IOSkywalkFamily.kext) make panic.


first issue 

https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/13227239/cda5570a-40ea-4ead-9238-8c50dcfb9b26

(HDMI) after verbose screen it's take 1-2 m before show MACOS login screen
(DisplayPort) after verbose screen the display lost signal and show message (DisplayPort no signal).

[Mac Pro.ioreg.zip](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/files/13839314/Mac.Pro.ioreg.zip)

<img width="1564" alt="Screenshot 2024-01-05 at 9 35 53 AM" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/13227239/809d77dd-905d-4b79-ac8f-5a6dc9fec686">

**Comment by 13thdemarch** [comment]
IOSkywalk and IO80211Legacy are for Broadcom 94360 Apple Wireless card. If you don't have, skip them.
Try this EFI. Also I changed the SMBIOS to MacPro7,1. You may want to replace the SMBIOS info.
[EFI.zip](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/files/13848132/EFI.zip)
If the issue isn't solved, you may want to try to reinstall macOS.

**Comment by niypoo** [comment]
@13thdemarch Thanks a lot,

I changed the EFI and Changed SMBIOS to MacPro7,1,
And still DisplayPort loses connection after boot, 

![404336040_238348075883135_8131301031581851100_n](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/13227239/4a91c303-f52f-4c7f-a24b-713fc75c6456)

**but I noticed after changed DisplayPort Stream options in monitor to 1.2 instead 1.4 the issue gone (until now its need more test),** 

_I know nothing about that if MACOS Sonoma support DisplayPort 1.4 or not_

**Comment by 13thdemarch** [comment]
interesting... this is the first time I've heard about this... And I don't know your monitor is 4K@60hz XD
I'm using the Gigabyte G42F 2 and HDMI to get FullHD@180Hz maximum (some DP cable is only 165hz I don't know why lol).
Please take more test and let me know if changed the DP stream to 1.2 instead of 1.4 will fix the issue.
