### ISSUE TITLE
Lan Intel Ethernet I-225V 

### ISSUE THREAD

**Issue by zwhyaa** [13thdemarch/b660m-aorus-pro-hackintosh#12]
你好，请问睡眠唤醒后网卡变成半双工是什么原因呢？

**Comment by 13thdemarch** [comment]
你能详细解释一下这个问题吗？

**Comment by zwhyaa** [comment]
> 你能详细解释一下这个问题吗？
<img width="706" alt="iShot_2024-01-10_15 31 58" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/70508685/23ab57c3-f61e-4412-8d36-8872c83887d4">
电脑正常睡眠后，唤醒电脑就会变成图片上这样，会由原来的全双工变成半双工，导致网速只有 100mbps

**Comment by 13thdemarch** [comment]
> 100mbps

您是否在起床后使用speedtest.net检查带宽？
之前和之后.

**Comment by zwhyaa** [comment]
> > 100mbps
> 
> 您是否在起床后使用speedtest.net检查带宽？ 之前和之后.

这是第一次启动时的测速
<img width="1159" alt="iShot_2024-01-10_15 41 45" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/70508685/484daafe-f3a2-444d-badf-94b1b6b2f059">
ran'ho然后这个睡眠过后唤醒后的测速
<img width="1141" alt="iShot_2024-01-10_15 44 32" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/70508685/41be302e-4da2-44aa-afb8-0f1cb6e5ed56">
bing'qie并且网卡就只会闪一个灯了
![Uploading 2024-01-10 15.45.46.jpg…]()

**Comment by zwhyaa** [comment]
![2024-01-10 15 45 46](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/70508685/4933a807-c152-4a2d-bf96-35ddbe8aa763)

**Comment by 13thdemarch** [comment]
有趣的...
我会看看!

**Comment by zwhyaa** [comment]
> 有趣的... 我会看看!

刚开始我以为是 BIOS 版本问题，切换到和您一样的版本还是有这个问题，我甚至怀疑是不是硬件问题？但是在Windows 系统睡眠唤醒，不会出现这个网卡问题。希望您有空的时候能看看，期待收到您的回复！感谢🙏

**Comment by zwhyaa** [comment]
> 有趣的... 我会看看!

我还尝试过使用 appleigc.kext这个网卡驱动，可以shui'mian

**Comment by 13thdemarch** [comment]
你试过AppleIGC.kext吗？

**Comment by zwhyaa** [comment]
> 你试过AppleIGC.kext吗？
appleigc睡眠唤醒后是全双工，但是表现为上不了网，而且电脑很卡。我在远景论坛没找到解决办法。用您的 efi 就是这个网卡会变成半双工我也觉得很奇怪
[Uploading efi.zip…]()
这个是我的 efi，如果方便看看有没有什么错误的地方请帮我指正，谢谢！

**Comment by zwhyaa** [comment]
> 你试过AppleIGC.kext吗？

appleigc睡眠唤醒后是全双工，但是表现为上不了网，而且电脑很卡。我在远景论坛没找到解决办法。用您的 efi 就是这个网卡会变成半双工我也觉得很奇怪。
[Uploading efi.zip…]()
这个是我的 efi，如果方便看看有没有什么错误的地方请帮我指正，谢谢！

**Comment by zwhyaa** [comment]
> 你试过AppleIGC.kext吗？

appleigc睡眠唤醒后是全双工，但是表现为上不了网，而且电脑很卡。我在远景论坛没找到解决办法。用您的 efi 就是这个网卡会变成半双工我也觉得很奇怪。

**Comment by zwhyaa** [comment]
> 你试过AppleIGC.kext吗？

现在就是 appleigc 驱动的
<img width="941" alt="iShot_2024-01-10_21 29 09" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/70508685/c06b94ac-26c6-4bb2-9f6f-73adc1f0ff29">
睡眠后，唤醒电脑表现为上不了网，不能重启或者关机，只能用机箱重启键重启。然后开机又可以正常使用了。
<img width="1358" alt="iShot_2024-01-10_21 32 43" src="https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/70508685/18800a44-e91f-42f8-8058-61f791798bde">

**Comment by zwhyaa** [comment]
[efi.zip](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/files/13888437/efi.zip)
这是我的 EFI 如果方便恳请您帮我查对一下是否有错误，非常感谢！

**Comment by 13thdemarch** [comment]
> [efi.zip](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/files/13888437/efi.zip) 这是我的 EFI 如果方便恳请您帮我查对一下是否有错误，非常感谢！

我会尽快看一下 👍🏻

**Comment by zwhyaa** [comment]
> > [efi.zip](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/files/13888437/efi.zip) 这是我的 EFI 如果方便恳请您帮我查对一下是否有错误，非常感谢！
> 
> 我会尽快看一下 👍🏻

好的非常感谢您

**Comment by 13thdemarch** [comment]
@zwhyaa 醒來後我的乙太網路很好🤔
前
![Screenshot 2024-01-11 at 23 58 25](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/59220499/840103d7-f91b-47ae-8c8a-56308966e218)
後
![Screenshot 2024-01-12 at 00 09 01](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/59220499/90e594ad-41b7-4795-b71d-bc0f2eed12f8)
你的EFI有一些問題:
- 不需要 SSDT-i225.aml.
- 僅使用AppleIGC或AppleIntelI210Ethernet.
例如你可以使用我的倉庫.

**Comment by zwhyaa** [comment]
> @zwhyaa 醒來後我的乙太網路很好🤔 前 ![Screenshot 2024-01-11 at 23 58 25](https://private-user-images.githubusercontent.com/59220499/295994805-840103d7-f91b-47ae-8c8a-56308966e218.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjk3NjAsIm5iZiI6MTcwNTAyOTQ2MCwicGF0aCI6Ii81OTIyMDQ5OS8yOTU5OTQ4MDUtODQwMTAzZDctZjkxYi00N2FlLThjOGEtNTYzMDg5NjZlMjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzMTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5Y2JhYjMyOWQ3YTc3OGI1M2M4ZmJmNGRkMWNiNmRmMDIxNjFhY2I5OTgyMzMxYTUyYTNjOTZkZTdiOTU0NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dqSr2flTHD0EXc-onGbNyw00vgJRe3pzraIMvauD-BY) 後 ![Screenshot 2024-01-12 at 00 09 01](https://private-user-images.githubusercontent.com/59220499/295994973-90e594ad-41b7-4795-b71d-bc0f2eed12f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjk3NjAsIm5iZiI6MTcwNTAyOTQ2MCwicGF0aCI6Ii81OTIyMDQ5OS8yOTU5OTQ5NzMtOTBlNTk0YWQtNDFiNy00Nzk1LWI3MWQtYmMwZjJlZWQxMmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzMTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MWE3Yzg5YmRmNWY0MWQyZjQ3NWQ1N2EwM2RiYjQ5YTNiOWUwNTZkNDlmODIwZWMyZmMxMmM0YzY4ZTAwZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kG7IJ0Qz2H25qEKckruQ_NShNyZvETt3Dna3W4S5vHs) 你的EFI有一些問題:
> 
> * 不需要 SSDT-i225.aml.
> * 僅使用AppleIGC或AppleIntelI210Ethernet.
>   例如你可以使用我的倉庫.

直接使用您的 EFI填入我的三码，测试结果还是和以前一样 @13thdemarch

**Comment by 13thdemarch** [comment]
真奇怪😂
這是我第一次遇到這種情況

**Comment by zwhyaa** [comment]
我怀疑网卡固件的原因，我准备去刷一下网卡固件

**Comment by zwhyaa** [comment]
> 真奇怪😂 這是我第一次遇到這種情況

您方便分享一下您的网卡固件版本吗？

**Comment by 13thdemarch** [comment]
> 我怀疑网卡固件的原因，我准备去刷一下网卡固件

你用的是modified韌體嗎？
我沒有更改任何有關乙太網路韌體和 BIOS 的內容 ;-;
@zwhyaa

**Comment by zwhyaa** [comment]
> > 我怀疑网卡固件的原因，我准备去刷一下网卡固件
> 
> 你用的是modified韌體嗎？ 我沒有更改任何有關乙太網路韌體和 BIOS 的內容 ;-; @zwhyaa

我以前通过这个帖子把固件刷成1.89
![QQ截图20240112112823](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/70508685/839c6fbf-e509-450c-b13b-70e184469f38)

**Comment by 13thdemarch** [comment]
> 我以前通过这个帖子把固件刷成1.89

這是...針對 Windows 的嗎？
macOS 不受影響 o.o

**Comment by zwhyaa** [comment]
> > 我以前通过这个帖子把固件刷成1.89
> 
> 這是...針對 Windows 的嗎？ macOS 不受影響 o.o

那是怎么回事呢我已经不知所措了，重装试试

**Comment by 13thdemarch** [comment]
> 那是怎么回事呢我已经不知所措了，重装试试

你可以嘗試使用我的EFI重新安裝
也按照我的指南配置BIOS👍

**Comment by zwhyaa** [comment]
我的bios是按照您的配置的，我用您的efi重装一下试试吧

**Comment by zwhyaa** [comment]
> > 那是怎么回事呢我已经不知所措了，重装试试
> 
> 你可以嘗試使用我的EFI重新安裝 也按照我的指南配置BIOS👍

机型需要改成MACPRO吗？我记得以前你设置的机型是imacpro

**Comment by 13thdemarch** [comment]
> 机型需要改成MACPRO吗？我记得以前你设置的机型是imacpro

目前我使用Mac Pro而不是iMacPro

**Comment by zwhyaa** [comment]
> > 机型需要改成MACPRO吗？我记得以前你设置的机型是imacpro
> 
> 目前我使用Mac Pro而不是iMacPro

好的

**Comment by zwhyaa** [comment]
> > > 机型需要改成MACPRO吗？我记得以前你设置的机型是imacpro
> > 
> > 
> > 目前我使用Mac Pro而不是iMacPro
> 
> 好的

今天刚好有时间，然后重装了系统用的您的EFI，网卡还是一样的问题，自从我刷了网卡固件就这样（不是网卡驱动）Intel现在貌似不允许降级固件了。破防直接格式化了硬盘，用不了一点黑苹果哈哈，老老实实用Windows了

**Comment by zwhyaa** [comment]
去找技嘉他们说没有新的固件，但是华硕这边放出了1.89固件。据说Intel已经更新到1.93了 。应该是我刷了1.89固件的问题。以前1.68都没问题。

**Comment by 13thdemarch** [comment]
@zwhyaa 你應該保留Aorus/Gigabyte的庫存固件，即使 LAN 是來自Intel的 🤣

**Comment by zwhyaa** [comment]
> @zwhyaa 你應該保留Aorus/Gigabyte的庫存固件，即使 LAN 是來自Intel的 🤣

没办法无法降级了😣
