### ISSUE TITLE
Sonoma 14.4 update gets KernelPanic

### ISSUE THREAD

**Issue by niypoo** [13thdemarch/b660m-aorus-pro-hackintosh#13]
Greetings ,

After updating to 14.4.1 my device gets KernelPanic , did you face this issue ?

**Comment by 13thdemarch** [comment]
![image](https://github.com/13thdemarch/b660m-aorus-pro-hackintosh/assets/59220499/e4d8848b-58c8-47e2-b776-9efa57b0e9b8)
No, mine is ok

**Comment by niypoo** [comment]
So that problem in wifi kext , thanks 🙏
