### ISSUE TITLE
MacOS Sequoia 

### ISSUE THREAD

**Issue by niypoo** [13thdemarch/b660m-aorus-pro-hackintosh#16]
Greetings ,
Hope all is well,
I would to ask you about "MacOS Sequoia" ! did you updated your hackintosh to Sequoia and is all working or there is any issue ?

**Comment by niypoo** [comment]
I have updated my device , after one day everything working sharm but notice that the IPhone mirroring isn't working.
<img width="630" alt="Screenshot 2024-09-18 at 9 57 01 AM" src="https://github.com/user-attachments/assets/a2dfddae-35dd-4eac-87c9-e922c6d27c14">

**Comment by 13thdemarch** [comment]
@niypoo Hi, sorry for late replying. I'm too busy irl.
My hack and Sequoia are fine. No issue.
The iPhone mirroring seems like for Apple Silicon devices only.
