### ISSUE TITLE
BIOS Configuration part

### ISSUE THREAD

**Issue by suxiaogang** [13thdemarch/b660m-aorus-pro-hackintosh#18]
My motherboard is Gigabyte B660M Gaming AC DDR4 which is very similar to yours. And the the BIOS Configuration part is almost the same.

But please check again some of the settings:
1. `Vt-d → Enabled`. In 99% cases on the hackintosh world, this supposed to be configurated as  `OFF`;
2. `Intel Platform Trust Technology(PTT) → Enabled`. Well, also in most cases this is `off` or `disabled`;
3. `Re-Size BAR`, not for sure, and you haven't mentioned.;

**Comment by 13thdemarch** [comment]
- For 1 and 2, they can be enabled starting from Ventura(?) for AppleVTD(?). They're working fine for me.
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/939b16cd-9605-499b-9994-6c07cc88c555" />

- About 3, if re-size BAR is enabled, it causes an error during the second sleep cycle. The computer wakes up, but the screen remains blank. I have to force a shutdown using the power button and then turn it on again. It might be a bug with my motherboard.
- Additionally, even though Aorus is a brand from Gigabyte, the BIOS configuration may be similar, but the code is different. If your configuration works fine, there's no need to change it.
