### ISSUE TITLE
RX6700xt support

### ISSUE THREAD

**Issue by kimduyminh** [13thdemarch/b660m-aorus-pro-hackintosh#19]
Can I use this EFI with RX6700xt gpu ?

**Comment by 13thdemarch** [comment]
Yes. Remember to remove my GPU properties and add kexts for 6700XT
![image](https://github.com/user-attachments/assets/4f2a08c4-d277-474d-8e1b-854b9296d60d)

**Comment by kimduyminh** [comment]
hmm where can I find the properties for my gpu ?

**Comment by 13thdemarch** [comment]
> hmm where can I find the properties for my gpu ?

It's optional, just for GPU fan customization and 4K screen. You can delete it.

**Comment by kimduyminh** [comment]
thank you
