### ISSUE TITLE
Need more test on some Aorus B660M Mobo

### ISSUE THREAD

**Issue by 13thdemarch** [13thdemarch/b660m-aorus-pro-hackintosh#2]
Recently with some basic researching, I found that my EFI maybe can work on the following mobos:
- B660M AORUS PRO AX
- B660M AORUS PRO
- B660M AORUS PRO AX DDR4
If anyone has one of those mobo, please feel free to test and let me know the result.
Cheer.

**Comment by ZQiannnn** [comment]
is any possible work with 13700k

**Comment by 13thdemarch** [comment]
> is any possible work with 13700k

Totally fine in my opinion. Just replace the CPU and try it out.
But one thing I'm not sure is about CPUID masking. But you can try my current mask for gen 13th. I will update if I have any infomation.

**Comment by tzy1106** [comment]
B660M AORUS PRO AX DDR4      wifi not work....

**Comment by 13thdemarch** [comment]
> B660M AORUS PRO AX DDR4 wifi not work....

I'm using BCM94360CD which is native with macOS. The AX mobo comes with Intel wifi card, so you may need the kexts for it. Please check [OpenIntelWireless](https://github.com/OpenIntelWireless) repo.
Also, to make bluetooth work with Intel card, you may use USBInjectAll.kext first instead of both UTBMap.kext and USBToolBox.kext. I will try to make another USB map if I have the result of AX mobo.

**Comment by tzy1106** [comment]
thanks for your direction. very much

**Comment by punjasin** [comment]
it freeze when booting ventura installation usb 
mine was 
i5 12gen
5700xt

**Comment by 13thdemarch** [comment]
> it freeze when booting ventura installation usb 
> 
> mine was 
> 
> i5 12gen
> 
> 5700xt

Please enable the verbose detail the error, panic, log file, etc... and your spec. What is your mobo.

**Comment by niypoo** [comment]
I have tested your EFI with some changes to work built-in wifi and bluetooth.
but I notice that 

1 - your CPU SCORE is Highest of mine I don't know  did I  do some wrong.
2- CPU Cores wrong in geekbanch it's read 20 cores .
3- mi mute mouse not connected via bluetooth any more.

**I need your help to create own USB MAP**



![Screenshot 2022-11-30 at 12 06 36 PM](https://user-images.githubusercontent.com/13227239/205287359-443a1381-cb0f-441d-9c41-5d7ef44e983b.png)
![Screenshot 2022-11-30 at 12 07 16 PM](https://user-images.githubusercontent.com/13227239/205287370-e79f890e-a00e-49c5-adf9-4508ac578034.png)
![Screenshot 2022-11-30 at 12 07 45 PM](https://user-images.githubusercontent.com/13227239/205287374-6030f0a1-613c-4e72-9ebc-d9370c1bf95d.png)
![Screenshot 2022-11-30 at 12 07 50 PM](https://user-images.githubusercontent.com/13227239/205287376-1e788bfc-1311-4564-b446-3160a9d070ff.png)

![Sc
![Screenshot 2022-11-30 at 12 08 19 PM](https://user-images.githubusercontent.com/13227239/205287380-646c25ee-ded8-4bad-90b2-68bb6af12f8c.png)
![Screenshot 2022-11-30 at 12 08 40 PM](https://user-images.githubusercontent.com/13227239/205287388-9625e9ba-1ab4-4323-b5aa-9183c7060c3a.png)
reenshot 2022-11-30 at 12 06 43 PM](https://user-images.githubusercontent.com/13227239/205287362-2451c698-ad69-4e5a-9f8e-ab9e4ba01f88.png)
![Screenshot 2022-11-30 at 12 06 57 PM](https://user-images.githubusercontent.com/13227239/205287364-266c6a44-7487-495d-a9ed-07f85d4dc340.png)
![Screenshot 2022-11-30 at 12 07 01 PM](https://user-images.githubusercontent.com/13227239/205287366-61f490c1-20aa-4b1c-8d43-59680f3e1d6c.png)
![Screenshot 2022-11-30 at 12 07 06 PM](https://user-images.githubusercontent.com/13227239/205287368-f0e5952d-d94e-4a38-be48-3e16e911422c.png)
![Screenshot 2022-11-30 at 11 37 51 PM](https://user-images.githubusercontent.com/13227239/205287352-5d618e94-8da2-452d-a0e0-1bdfb52fdc7e.png)
![Screenshot 2022-11-30 at 11 37 57 PM](https://user-images.githubusercontent.com/13227239/205287355-9a9aedf6-3db4-46e1-ba6b-f008f064104b.png)
![Screenshot 2022-11-30 at 12 06 31 PM](https://user-images.githubusercontent.com/13227239/205287356-b74eb9e1-5f1d-4e45-bdf7-18588ed72dea.png)



 
![Screenshot 2022-11-30 at 11 37 47 PM](https://user-images.githubusercontent.com/13227239/205287335-351fa1a7-6297-48eb-9f8f-977b63d0c489.png)

**Comment by 13thdemarch** [comment]
> I have tested your EFI with some changes to work built-in wifi and bluetooth. but I notice that
> 
> 1 - your CPU SCORE is Highest of mine I don't know did I do some wrong. 2- CPU Cores wrong in geekbanch it's read 20 cores . 3- mi mute mouse not connected via bluetooth any more.
> 
> **I need your help to create own USB MAP**
> 
> ![Screenshot 2022-11-30 at 12 06 36 PM](https://user-images.githubusercontent.com/13227239/205287359-443a1381-cb0f-441d-9c41-5d7ef44e983b.png) ![Screenshot 2022-11-30 at 12 07 16 PM](https://user-images.githubusercontent.com/13227239/205287370-e79f890e-a00e-49c5-adf9-4508ac578034.png) ![Screenshot 2022-11-30 at 12 07 45 PM](https://user-images.githubusercontent.com/13227239/205287374-6030f0a1-613c-4e72-9ebc-d9370c1bf95d.png) ![Screenshot 2022-11-30 at 12 07 50 PM](https://user-images.githubusercontent.com/13227239/205287376-1e788bfc-1311-4564-b446-3160a9d070ff.png)
> 
> ![Sc Screenshot 2022-11-30 at 12 08 19 PM Screenshot 2022-11-30 at 12 08 40 PM reenshot 2022-11-30 at 12 06 43 PM](https://user-images.githubusercontent.com/13227239/205287362-2451c698-ad69-4e5a-9f8e-ab9e4ba01f88.png) ![Screenshot 2022-11-30 at 12 06 57 PM](https://user-images.githubusercontent.com/13227239/205287364-266c6a44-7487-495d-a9ed-07f85d4dc340.png) ![Screenshot 2022-11-30 at 12 07 01 PM](https://user-images.githubusercontent.com/13227239/205287366-61f490c1-20aa-4b1c-8d43-59680f3e1d6c.png) ![Screenshot 2022-11-30 at 12 07 06 PM](https://user-images.githubusercontent.com/13227239/205287368-f0e5952d-d94e-4a38-be48-3e16e911422c.png) ![Screenshot 2022-11-30 at 11 37 51 PM](https://user-images.githubusercontent.com/13227239/205287352-5d618e94-8da2-452d-a0e0-1bdfb52fdc7e.png) ![Screenshot 2022-11-30 at 11 37 57 PM](https://user-images.githubusercontent.com/13227239/205287355-9a9aedf6-3db4-46e1-ba6b-f008f064104b.png) ![Screenshot 2022-11-30 at 12 06 31 PM](https://user-images.githubusercontent.com/13227239/205287356-b74eb9e1-5f1d-4e45-bdf7-18588ed72dea.png)
> 
> ![Screenshot 2022-11-30 at 11 37 47 PM](https://user-images.githubusercontent.com/13227239/205287335-351fa1a7-6297-48eb-9f8f-977b63d0c489.png)

Thank you for your feedback.
About 1 and 2, there is a small change in the EFI that I will release in the next version of OC in this month (maybe next week).
About the 3, seems like you are using Intel wifi card on AX mobo. I will try my best to create the USB map kext and let you know soon.

**Comment by niypoo** [comment]
Thanks taruyato for your effort,
I noticed also that by using CpuTopologyRebuild & CpuTscSync kexts my CPU in Geekbanch read 12-cores and 20 threads and this is correct but the score never changes.

and I don't know should I used them with CPUFriend & CPUFriendDataProvider or use them alone !!,

And I'm waiting USB Map to test , thank you again and take your time.

**Comment by 13thdemarch** [comment]
> Thanks taruyato for your effort, I noticed also that by using CpuTopologyRebuild & CpuTscSync kexts my CPU in Geekbanch read 12-cores and 20 thirds and this is correct but the score never changes.
> 
> and I don't know should I used them with CPUFriend & CPUFriendDataProvider or use them alone !!,
> 
> And I'm waiting USB Map to test , thank you again and take your time.

1. Yes, the CpuTopologyRebuild will correct the cores and the threads, with Hyper-Threading is enabled in the BIOS. Also please remove the CpuTscSync, not need on our system and I don't cover the issue with that kext.
2. CPUFriend & CPUFriendDataProvider should be paired together. And please don't care too much about the CPU Geekbench score. If it is from 1600 to 1800 or even higher a bit, that's totally fine. This is Hackintosh and number is just number ;)
3. Here is the USB kext. It should be paired with USBToolBox.kext.
[UTBMap.kext.zip](https://github.com/taruyato/b660m-aorus-pro-ddr4-hackintosh/files/10141401/UTBMap.kext.zip)

**Comment by niypoo** [comment]
I forget to mention that my motherboard is **"b660m aorus pro ax ddr4"** :),

about that "remove CpuTscSync" !! even in Monterey 12 or only in Venture 13 Os !!?

Thank you about "USB Map" I will test it now.

**Comment by 13thdemarch** [comment]
> I forget to mention that my motherboard is **"b660m aorus pro ax ddr4"** :),
> 
> about that "remove CpuTscSync" !! even in Monterey 12 or only in Venture 13 Os !!?
> 
> Thank you about "USB Map" I will test it now.

CpuTscSync is not needed on any OS version. Please remove it.

**Comment by niypoo** [comment]
Please see the Kexts folder in Monterey Os is there any kext not needed!

![Screen Shot 2022-12-02 at 3 42 31 PM](https://user-images.githubusercontent.com/13227239/205306058-8233128f-06ac-45e6-a436-0a652b41c564.png)

**Comment by 13thdemarch** [comment]
> Please see the Kexts folder in Monterey Os is there any kext not needed!
> 
> ![Screen Shot 2022-12-02 at 3 42 31 PM](https://user-images.githubusercontent.com/13227239/205306058-8233128f-06ac-45e6-a436-0a652b41c564.png)

Just use every kexts which are included in my repo, also add necessary kexts for Intel wireless card. That's all.

**Comment by niypoo** [comment]
I Think I added all "necessary kexts for Intel wireless card" and just remove GPU Sensors Kext !? is there any kexts missing ?

**Comment by niypoo** [comment]
The kext that have blue color for  Bluetooth and red for wifi

**Comment by 13thdemarch** [comment]
> I Think I added all "necessary kexts for Intel wireless card" and just remove GPU Sensors Kext !? is there any kexts missing ?
![205306058-8233128f-06ac-45e6-a436-0a652b41c564](https://user-images.githubusercontent.com/59220499/205307364-397eb7c6-862a-4b93-adf2-9363b3fb3d63.png)

remove those

**Comment by niypoo** [comment]
about config.plist file please can you check it , maybe I did some wrong also in it

**My device components**
Gigabyte Aorus b660m pro ax ddr4
i7-12700F 2.11 GHz 12-Core Intel Core i7
AMD Radeon RX 5500 XT 8 GB
16 GB 3600 MHz DDR4

**Comment by niypoo** [comment]
and this code your code If I enabled it ! it will works with my GPU or works only 6 series ?

![Screen Shot 2022-12-02 at 4 09 30 PM](https://user-images.githubusercontent.com/13227239/205311379-ac9efec2-200c-4692-99ca-1b3ca5d970dd.png)

**Comment by 13thdemarch** [comment]
> about config.plist file please can you check it , maybe I did some wrong also in it
> 
> **My device components** Gigabyte Aorus b660m pro ax ddr4 i7-12700F 2.11 GHz 12-Core Intel Core i7 AMD Radeon RX 5500 XT 8 GB 16 GB 3600 MHz DDR4
> 
> [config.plist.zip](https://github.com/taruyato/b660m-aorus-pro-ddr4-hackintosh/files/10141615/config.plist.zip)

Please follow my config.



> and this code your code If I enabled it ! it will works with my GPU or works only 6 series ?
> 
> ![Screen Shot 2022-12-02 at 4 09 30 PM](https://user-images.githubusercontent.com/13227239/205311379-ac9efec2-200c-4692-99ca-1b3ca5d970dd.png)

That patch is only for AMD 6000 Series to disable the ZeroRPM to make the GPU cooler. It's optional.

**Comment by niypoo** [comment]
So USB Map working nicely even usb-type c now is working except 1 usb 3.2 the red one that placed beside USB-Type C is not working,

Thank You ..

**Comment by 13thdemarch** [comment]
> So USB Map working nicely even usb-type c now is working except 1 usb 3.2 the red one that placed beside USB-Type C is not working,
> 
> Thank You ..

that one is for BIOS flashing recovery (I guess) so we don't need it lol

**Comment by niypoo** [comment]
I'm facing weird issue with android emulator it's a black screen, and I did some search folks says that , enable virtualization but I not found this option in bios or config.plist !! did you know about that ?

**Comment by 13thdemarch** [comment]
> I'm facing weird issue with android emulator it's a black screen, and I did some search folks says that , enable virtualization but I not found this option in bios or config.plist !! did you know about that ?

I don't cover other issues such as emulator, virtualisation, etc... because I don't use them. Please let me know if you know how to fix them.

**Comment by niypoo** [comment]
another issue I have facing now randomly the os freezing 2 seconds and working 2 seconds many times then wholy freezing and make restart.

did you facing issue like that ?

**Comment by 13thdemarch** [comment]
> another issue I have facing now randomly the os freezing 2 seconds and working 2 seconds many times then wholy freezing and make restart.
> 
> did you facing issue like that ?

No, my system is totally fine.

**Comment by niypoo** [comment]
Sorry @taruyato but I have two questions ,
1- in your screenshots there is GPU and CPU Gadgets ! how can I display them? 
2- I have tried to update bios but the usb flash not show in bios screen , I change flash usb format from (ExFat) to Mac OS extended also not displayed !

**Comment by lanyangyang1999** [comment]
I use 12100, 5700xt,GIGABYTE-b660m-d2h,and use it to install ventura13.0.1,intall is successfully,but when it reboot,cant stop reboot,and can't go OC system,I dont know why，screen show : LOG:RESET:RECOVERY
![Screenshot_20221211_204555_Gallery](https://user-images.githubusercontent.com/100829491/206948013-3d75ce85-fdb3-45e5-aa06-ad0191bc59f1.jpg)

**Comment by 13thdemarch** [comment]
> I use 12100, 5700xt,GIGABYTE-b660m-d2h,and use it to install ventura13.0.1,intall is successfully,but when it reboot,cant stop reboot,and can't go OC system,I dont know why，screen show : LOG:RESET:RECOVERY ![Screenshot_20221211_204555_Gallery](https://user-images.githubusercontent.com/100829491/206948013-3d75ce85-fdb3-45e5-aa06-ad0191bc59f1.jpg)

try to reset nvram, also check Dortania for more information about issue with OC. And my repo is for mobo from AORUS, not Gigabyte. They are not same.

**Comment by lanyangyang1999** [comment]
Ok，I will try other,thank you

**Comment by SarthakDhonchak** [comment]
Hi @taruyato 
I'm trying to run this on B660M AORUS PRO AX without any external GPU.
But can't get it to boot or even show up in boot options.

What changes do you suggest I make, and is it even doable on iGPU, I can't find any guides/help regarding this.

My device components
Gigabyte Aorus b660m pro ax ddr4
i5-12400
intel® UHD Graphics 730
16 GB 3600 MHz DDR4

**Comment by 13thdemarch** [comment]
> Hi @taruyato 
> 
> I'm trying to run this on B660M AORUS PRO AX without any external GPU.
> 
> But can't get it to boot or even show up in boot options.
> 
> 
> 
> What changes do you suggest I make, and is it even doable on iGPU, I can't find any guides/help regarding this.
> 
> 
> 
> My device components
> 
> Gigabyte Aorus b660m pro ax ddr4
> 
> i5-12400
> 
> intel® UHD Graphics 730
> 
> 16 GB 3600 MHz DDR4

500 and 600 mobo series have to need graphic card. If not you can use Hackintosh.
Also, UHD730 is unsupported.

**Comment by SarthakDhonchak** [comment]
I got a 6600 xt and used EFI from helloworlde's fork of your repo  https://github.com/helloworlde/b660m-aorus-pro-hackintosh
I was able to intall mac OS Ventura and get it to boot but my wi-fi and Bluetooth are not working and I can't figure out why or troubleshoot the cause of why they are not working.

Any suggestions on what i can do to make my bluetooth and wi-fi working?

**Comment by niypoo** [comment]
> I got a 6600 xt and used EFI from helloworlde's fork of your repo https://github.com/helloworlde/b660m-aorus-pro-hackintosh I was able to intall mac OS Ventura and get it to boot but my wi-fi and Bluetooth are not working and I can't figure out why or troubleshoot the cause of why they are not working.
> 
> Any suggestions on what i can do to make my bluetooth and wi-fi working?

you use some extra kext to make them work 

**AirportItlwm.kext** for enable wifi (not stable in venture)
**BlueToolFixup.kext & intelbtpatcher.kext & IntelBluetoothFirmware.kext** for enable Bluetooth,

and this EFI Folder is mine for Monetary 
https://github.com/niypoo/gigabyte-b660m-aorus-pro-ax-ddr4-monterey-hackintosh

**Comment by SarthakDhonchak** [comment]
> > I got a 6600 xt and used EFI from helloworlde's fork of your repo https://github.com/helloworlde/b660m-aorus-pro-hackintosh I was able to intall mac OS Ventura and get it to boot but my wi-fi and Bluetooth are not working and I can't figure out why or troubleshoot the cause of why they are not working.
> > Any suggestions on what i can do to make my bluetooth and wi-fi working?
> 
> you use some extra kext to make them work
> 
> **AirportItlwm.kext** for enable wifi (not stable in venture) **BlueToolFixup.kext & intelbtpatcher.kext & IntelBluetoothFirmware.kext** for enable Bluetooth,
> 
> and this EFI Folder is mine for Monetary https://github.com/niypoo/gigabyte-b660m-aorus-pro-ax-ddr4-monterey-hackintosh

I've already tried https://github.com/niypoo/gigabyte-b660m-aorus-pro-ax-ddr4-monterey-hackintosh but it doesn't boot, shows a black screen and URL to apple's support site http://support.apple.com/mac/startup
![image](https://user-images.githubusercontent.com/55049826/209928644-d6e3030e-0170-4095-a4f4-f411fb7d9fe4.png)

**Comment by niypoo** [comment]
> > > I got a 6600 xt and used EFI from helloworlde's fork of your repo https://github.com/helloworlde/b660m-aorus-pro-hackintosh I was able to intall mac OS Ventura and get it to boot but my wi-fi and Bluetooth are not working and I can't figure out why or troubleshoot the cause of why they are not working.
> > > Any suggestions on what i can do to make my bluetooth and wi-fi working?
> > 
> > 
> > you use some extra kext to make them work
> > **AirportItlwm.kext** for enable wifi (not stable in venture) **BlueToolFixup.kext & intelbtpatcher.kext & IntelBluetoothFirmware.kext** for enable Bluetooth,
> > and this EFI Folder is mine for Monetary https://github.com/niypoo/gigabyte-b660m-aorus-pro-ax-ddr4-monterey-hackintosh
> 
> I've already tried https://github.com/niypoo/gigabyte-b660m-aorus-pro-ax-ddr4-monterey-hackintosh but it doesn't boot, shows a black screen and URL to apple's support site http://support.apple.com/mac/startup ![image](https://user-images.githubusercontent.com/55049826/209928644-d6e3030e-0170-4095-a4f4-f411fb7d9fe4.png)

**so best solution for you search for the kexts that I have told you names and get the last versions,
you can do it by **opencore configurator app** and wifi & bluetooth will work ,**

if you want Monetary you can add **-v in boot-arg** to show error that make that screen with you

**Comment by SarthakDhonchak** [comment]
@niypoo @naratouma526 
I've tried everything I could find on open core's guide and forum. I've also tried https://github.com/OpenIntelWireless/itlwm

I have bluetooth working now, but still the WiFi is not working.
I've added my EFI files here https://github.com/SarthakDhonchak/Gigabyte-B660M-AORUS-PRO-AX-DDR4-HACKINTOSH

Can you please help in figuring out what could be wrong and why the motherboard's WiFi is not working? 
I will really appreciate it 😄

**Comment by 13thdemarch** [comment]
> @niypoo @naratouma526 I've tried everything I could find on open core's guide and forum. I've also tried https://github.com/OpenIntelWireless/itlwm
> 
> I have bluetooth working now, but still the WiFi is not working. I've added my EFI files here https://github.com/SarthakDhonchak/Gigabyte-B660M-AORUS-PRO-AX-DDR4-HACKINTOSH
> 
> Can you please help in figuring out what could be wrong and why the motherboard's WiFi is not working? I will really appreciate it 😄

I won't cover any fork repo unless you're thinking your EFI repo is correct.
I tried to make my EFI is very universal for many B660M Aorus mobo so only you have to do is just grab Intel kexts and put them into it. Please the FAQs and other docs about Intel kext carefully.

**Comment by niypoo** [comment]
Hey, now I'm facing an issue and I would ask you if you faced it or not, the issue is HDMI cable video is working good but without audio !

**Comment by 13thdemarch** [comment]
> Hey, now I'm facing an issue and I would ask you if you faced it or not, the issue is HDMI cable video is working good but without audio !

You mean digital audio via HDMI? Mine is ok. Check your HDMI cable and your monitor if supported. I'm using Samsung TV and everything works correctly.

**Comment by niypoo** [comment]
> > Hey, now I'm facing an issue and I would ask you if you faced it or not, the issue is HDMI cable video is working good but without audio !
> 
> You mean digital audio via HDMI? Mine is ok. Check your HDMI cable and your monitor if supported. I'm using Samsung TV and everything works correctly.

yes, unfortunately monitor support and in windows sound out from monitor .. so I'm looking for solution for this  .

**Comment by Williamtung1** [comment]
I have a B660M Aorus Elite AX from Gigabyte. In general, I think your EFI would fit my motherboard.
Adding the kexts for Intel Wi-Fi, and Realtek Ethernet, remapping USB Ports, and Making one's own CPU power management data for CPUFriend would do.

For ACPI, I had a look and I am really interested in it. (Finally, somebody who can actually write ACPI) I think you have added a few extra devices like GMI0, SRAM, XSPI, PTC0, IUC0, DMI0, PMT0, URT0, etc. What exactly are they? Are they just apple-exclusive devices or are they actually useful?

Btw, I think you are very lucky to have better firmware, it seems. I have got all sorts of sleep issues and shutdown issues with my firmware. (I can't even properly startup without fixing KASLR, )

**Comment by 13thdemarch** [comment]
> I have a B660M Aorus Elite AX from Gigabyte. In general, I think your EFI would fit my motherboard.
> 
> Adding the kexts for Intel Wi-Fi, and Realtek Ethernet, remapping USB Ports, and Making one's own CPU power management data for CPUFriend would do.
> 
> 
> 
> For ACPI, I had a look and I am really interested in it. (Finally, somebody who can actually write ACPI) I think you have added a few extra devices like GMI0, SRAM, XSPI, PTC0, IUC0, DMI0, PMT0, URT0, etc. What exactly are they? Are they just apple-exclusive devices or are they actually useful?
> 
> 
> 
> Btw, I think you are very lucky to have better firmware, it seems. I have got all sorts of sleep issues and shutdown issues with my firmware. (I can't even properly startup without fixing KASLR, )

Thank you for your comment. They are actually new devices on new generation motherboard, start from Alder Lake. I added all of them in the SSDT for macOS, maybe just for useful I guess lol 😹.
I'm testing a new EFI which I changed and patched a lot of things for system stability and sleep optimisation.
And you are right, not only your mobo has some weird issues with sleeping. I don't know why Gigabyte removed some options in BIOS such as Wake from USB, etc... which are already existed on old gen mobo. They are very important for fixing sleep. I had to do many things manually on macOS to make it sleep completely but seems not ok ;-;.
I think you can update your BIOS to latest version then re-configure the BIOS again and try. And if you don't mind, can you send me the Elite mobo original DSDT? I think I can make something very interesting.

**Comment by Williamtung1** [comment]
My BIOS is already on the latest version.(F21) May I ask if the method of "patching a lot of things" is further patching and implementing the _PTS, _Wak and _TTS methods? I would be very glad if you can help me to do so.  My EFI and unmodified DSDT are uploaded to my repo https://github.com/Williamtung1/Gigabyte-B660M-AORUS-ELITE-Hackintosh

**Comment by 13thdemarch** [comment]
> My BIOS is already on the latest version. May I ask if the method of "patching a lot of things" is further patching and implementing the _PTS, _Wak and _TTS methods? I would be very glad if you can help me to do so. My EFI and unmodified DSDT are uploaded to my repo https://github.com/Williamtung1/Gigabyte-B660M-AORUS-ELITE-Hackintosh

PTS, WAK and TTS are not needed 😁👍. I will check the original DSDT and let you know the result soon.

**Comment by 13thdemarch** [comment]
@Williamtung1 Seems your EFI has many unnecessary SSDT, some of them are for laptop... Also I can't find the original DSDT.

**Comment by Williamtung1** [comment]
Sorry, I was dumping my ACPI just now and I have uploaded them now

**Comment by Williamtung1** [comment]
I wasn't expecting with such speedy responses

**Comment by Williamtung1** [comment]
May I ask which of them is unnecessary? (Probably XOSI, ALS0, ARTC, right?)

**Comment by Williamtung1** [comment]
Can you tell me how did you manage to patch your system to stability, please? I can't find much information on this matter anywhere. Any help would be much appreciated.

**Comment by 13thdemarch** [comment]
> Can you tell me how did you manage to patch your system to stability, please? I can't find much information on this matter anywhere. Any help would be much appreciated.

First I think you should understand every essential patches first. I have used Hackintosh for 3 years so it is very hard to explain what I did with my patch.

**Comment by Williamtung1** [comment]
I can understand most basic patches, I mean, can you please teach me? I know what they are for(ie. EC,USBX, PLUG, RTC, etc)
Btw, the SSDTs you said are not needed contain mainly cosmetic macOS-only device
I have used Hackinotsh for almost 4 years, as a matter of fact. (Unfortunately, I don't have as much knowledge as you do.)

**Comment by 13thdemarch** [comment]
@Williamtung1 Take my current SSDT. Also using the original DSDT and create FixHPET, FixIRQ from SSDTTime and try, remember to add OC patches. Just 3 of them are ok. The original DSDT of Elite mobo is not much different, I think I can create an universal SSDT for both Elite and Pro mobo.

**Comment by Williamtung1** [comment]
OK, I will try now

**Comment by 13thdemarch** [comment]
> OK, I will try now

You can use my EFI for example, except USB mapping kext. It's for Pro mobo.

**Comment by Williamtung1** [comment]
As a matter of fact, I have already done FixHPET already. Anyways, I will do that again to see if there are any changes
My EFI has no problem other than Wake or shutdown issues. I think my SSDT basically does the same as yours, other than a few extra methods I have stated in other comments and a few for thunderbolt, I think

**Comment by Williamtung1** [comment]
The second sleep cycle failed as expected
2023-03-15 15:16:07 +0000 Failure             	Failure during sleep: 0x0000001F : EFI/Bootrom Failure after last point of entry to sleep

**Comment by 13thdemarch** [comment]
> Second Sleep Cycle failed as expected

I won't cover Sleep/Wake issues 👍🏻

**Comment by Williamtung1** [comment]
I mean, can you at least give a hint how did you manage to have Sleep/Wake working, please

**Comment by 13thdemarch** [comment]
> I mean, can you at least give a hint how did you managed to have Sleep/Wake woking

Everything you need is on Dortania site ;-;. Specially is USB mapping.

**Comment by Williamtung1** [comment]
I have mapped my USB properly, for your information. More resources are available outside of Dortania as well
what I thought was that you did your own ACPI editing to get you sleep working
![Screenshot 2023-03-15 at 15 25 12](https://user-images.githubusercontent.com/96200327/225358207-77564d8a-b1a7-4cb8-92de-1c31685a992a.png)

**Comment by Williamtung1** [comment]
As a last question, did you manage to get a perfect sleep? If so, can you share your SSDT(if the version on GitHub is not the latest) Thank you very much, anyways

**Comment by 13thdemarch** [comment]
> As a last question, did you manage to get a perfect sleep? If so, can you share your SSDT(if the version on GitHub is not the latest) Thank you very much, anyways

[SSDT-AORUS-B660M.aml.zip](https://github.com/serouin/b660m-aorus-pro-hackintosh/files/10981832/SSDT-AORUS-B660M.aml.zip)



> I have mapped my USB properly, for your information. More resources are available outside of Dortania as well what I thought was that you did your own ACPI editing to get you sleep working ![Screenshot 2023-03-15 at 15 25 12](https://user-images.githubusercontent.com/96200327/225358207-77564d8a-b1a7-4cb8-92de-1c31685a992a.png)

Your map is not correct.

**Comment by Williamtung1** [comment]
May I ask what is wrong? I don't realise what is wrong with my map. Can you give me some indications?

**Comment by 13thdemarch** [comment]
I will close this thread and open other helping threads.

**Comment by GoogleQian** [comment]
> I use 12100, 5700xt,GIGABYTE-b660m-d2h,and use it to install ventura13.0.1,intall is successfully,but when it reboot,cant stop reboot,and can't go OC system,I dont know why，screen show : LOG:RESET:RECOVERY ![Screenshot_20221211_204555_Gallery](https://user-images.githubusercontent.com/100829491/206948013-3d75ce85-fdb3-45e5-aa06-ad0191bc59f1.jpg)

me too,  Have you solved it yet?
