### ISSUE TITLE
Never wake up from second sleep

### ISSUE THREAD

**Issue by niypoo** [13thdemarch/b660m-aorus-pro-hackintosh#3]
I'm facing now issue with sleep and wake up,
first time the case and processor fans off and the screen putted in stand by mode, and it's wake up successfully by mouse click or bluetooth keyboard tap.

but in second time the case and processor fans not off and  the screen putted in stand by mode, but never wake up by mouse or keyboard even remove and insert HDMI Cable or turn screen off and on again.

  
![Screenshot 2022-12-07 at 1 42 21 PM](https://user-images.githubusercontent.com/13227239/206170812-a3c5d247-e6b9-4571-b659-421a0d00536f.png)

**Comment by 13thdemarch** [comment]
```
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0
sudo pmset proximitywake 0
sudo pmset tcpkeepalive 0
```

Run those, disable Wake from network access. Also if cant wake by mouse or keyboard, you may want to use power button instead.

**Comment by niypoo** [comment]
> ```
> sudo pmset autopoweroff 0
> sudo pmset powernap 0
> sudo pmset standby 0
> sudo pmset proximitywake 0
> sudo pmset tcpkeepalive 0
> ```
> 
> 
>     
>   
> 
> Run those, disable Wake from network access. Also if cant wake by mouse or keyboard, you may want to use power button instead.

Mouse and keyboard first time working as charm but second sleep none even power button never make pc wake up I have to restart or shutdown it.

**Comment by 13thdemarch** [comment]
I won't cover this issue. My system is totally fine as I said before. The SSDT is universal for gen 12-13th Intel CPU. So please check your system.

**Comment by niypoo** [comment]
> I won't cover this issue. My system is totally fine as I said before. The SSDT is universal for gen 12-13th Intel CPU. So please check your system.

I know , even My bios I have changed the value as you mentioned , so I don't know where is the issue maybe in extra kexts for bluetooth and wifi I will test that remove them and test

**Comment by 13thdemarch** [comment]
@niypoo Thank you for this issue. Seems like the problem is from Gigabyte lastest UEFI firmware on this motherboard, and it's cause by Above 4G and Re-size BARS. Everything was fine with me with older firmware version.
Also set them back to **Auto** by default is solved this problem.
Thank you once again and so sorry about closing the issue very soon 🙇‍♂️

**Comment by niypoo** [comment]
no problem, thanks for your efforts
