### ISSUE TITLE
Why Serial Port enabled

### ISSUE THREAD

**Issue by koli998** [13thdemarch/b660m-aorus-pro-hackintosh#4]
`Super IO Configuration > Serial Port: Enabled`
but I search from internet, many documents recommends the `Serial Port` set to be disabled, so why you set it to be enabled.

**Comment by 13thdemarch** [comment]
> `Super IO Configuration > Serial Port: Enabled`
> 
> but I search from internet, many documents recommends the `Serial Port` set to be disabled, so why you set it to be enabled.
> 
> 

Seem Serial Port will cause the issue with Apple Watch unlock... I thought it need for fan sensor so I enabled it lol. Thank you for the info, I will update the BIOS configuration in the update next month! 😉
