### ISSUE TITLE
USB randomly stop working

### ISSUE THREAD

**Issue by koli998** [13thdemarch/b660m-aorus-pro-hackintosh#5]
I bought a hackintosh machine online, seller's technicians also configured the opencore. 

mainboard: gigabyte b660m aorus pro d4
cpu: 13700kf
graphics card: amd 6600xt

There is a problem that bothers me, that is, the keyboard and mouse will suddenly not working. At this time, all usbs are not working, and it is useless to unplug and plug again.  But the computer is still working. This happens about once a day.

I asked the seller's technicians and they were not sure what the problem was either, they tried change the kext of usb mapping from USBToolBox.kext to USBPorts.kext. The frequency of this problem has decreased, and this problem has only happened once in the past few days.

I checked the relevant information on the Internet, some said it was a problem with the Gigabyte motherboard, and some said it was a problem caused by Bluetooth.

https://www.tonymacx86.com/threads/gigabyte-z690-aero-g-i5-12600k-amd-rx-6800-xt.317179/page-235#post-2361106
https://www.reddit.com/r/hackintosh/comments/lvlc88/usb_randomly_stops_working/

In the situation that only happened once these days, I found the bluetoothd crash reports.

![img](https://user-images.githubusercontent.com/128103303/225780853-8455d39b-2671-47a4-a2d9-89c6e58f051f.png)
![img](https://user-images.githubusercontent.com/128103303/225781762-05d80a2a-d0e7-4afa-88de-eb8d47aaed0f.png)

![img](https://user-images.githubusercontent.com/128103303/225782037-76714c95-3d36-4ce7-a6bd-b516abd3cc9d.png)

![img](https://user-images.githubusercontent.com/128103303/225783268-138aa2b6-5e3a-456c-a6be-cdbdfbc4f00d.png)

So do you have any idea?

**Comment by 13thdemarch** [comment]
I know this issue. It happened with my old laptop Dell G7 7588 before. I don't know how to fix it and randomly when I plug some devices such as keyboard, mouse,... from 3.0 port to 2.0 port and everything is fine ;-;
Can you send me your email? I will send you my current EFI which changed and patched a lot of thing for improving sleep and fixing some stuffs. You can help me for testing it and let me know the result. Let keep this thread open.

**Comment by 13thdemarch** [comment]
Also try to update the BIOS to the latest version and re-config it. I think I should update the BIOS configuration now.

**Comment by koli998** [comment]
My BIOS version is latest. It happened again just a while ago. And bluetoothd crash agagin. I am looking at the launchd.log to find some useful information.
[launchd.log](https://github.com/serouin/b660m-aorus-pro-hackintosh/files/10996911/launchd.log)

**Comment by 13thdemarch** [comment]
What wireless card are you using?

**Comment by koli998** [comment]
I only know that it is Broadcom's wireless card, but I don't know the specific model.
BCM4360 802.11ac Wireless Network Adapter:

Bluetooth Chipset:	BCM_20702B0
I found this information in system information.

**Comment by 13thdemarch** [comment]
How many antenas does it have?

**Comment by koli998** [comment]
three

**Comment by 13thdemarch** [comment]
It's BCM943602CS. That's ok.
Let try the following test:
- Plug all HID devices like keyboard, mouse to the 2.0 hub port (They are on the top of the back IO).
- The wireless card will be plugged to the first usb port from left to right on the motherboard. This is my current port for my wireless card, and new USB mapping is configured for it.
- Don't plug any charging or others USB device, just mouse and keyboard.
- Try to change other mouse device if you are using 2.4ghz wireless mouse, like a wired mouse. It happened to me before on this motherboard when I used Logitech G304 wireless mouse.
Also please send me your email so I can send you my current EFI, not the version on Github.

**Comment by koli998** [comment]
qutend[#]hotmail.com

**Comment by koli998** [comment]
Yes, I only plug the keyboard and mouse to the 2.0 hub port. There is no wireless mouse.

The second one I'll have to research as I'm new to the hardware.

**Comment by 13thdemarch** [comment]
> qutend[#]hotmail.com

Sent. Please fill the SMBIOS info. Also this is just a test version. I will update the final version on the update next month.

**Comment by 13thdemarch** [comment]
> Yes, I only plug the keyboard and mouse to the 2.0 hub port. There is no wireless mouse.
> 
> The second one I'll have to research as I'm new to the hardware.

Feel free. And I updated the new configuration for the BIOS, you can follow it.
If everything is exactly what I tell you but the issue is still happened, you may want to check the wireless card and its adapter 😿

**Comment by koli998** [comment]
Thank you. I will try to follow your BIOS.

**Comment by koli998** [comment]
BCM94360CS
