### ISSUE TITLE
USB Type C connectivity issues

### ISSUE THREAD

**Issue by SarthakDhonchak** [13thdemarch/b660m-aorus-pro-hackintosh#7]
Hi,
Thank you for your awesome work :-)

I was facing some weird connectivity issue with some of my devices.

It seems that the type c port on the back of the motherboard is working only in USB 3.0+ standards, and not recognizing devices that support only USB 2.0 or prior.
Is there a way to fix this?

**Comment by 13thdemarch** [comment]
[USB Fix.zip](https://github.com/serouin/b660m-aorus-pro-hackintosh/files/10997993/USB.Fix.zip)
Try this. Remove USBToolBox.kext and UTBMap.kext, replace XHCI-Unsupported.kext with the version in the zip file.
Remember to snapshot config.plist again.

**Comment by 13thdemarch** [comment]
[USBPorts.kext.zip](https://github.com/serouin/b660m-aorus-pro-hackintosh/files/10998021/USBPorts.kext.zip)
If you are using AX mobo, use this one instead of the one in that zip.

**Comment by SarthakDhonchak** [comment]
Thanks,
Yes I'm using the AX motherboard, I'll check this out tomorrow.

Is there any other change you think I should do for thr AX board?

**Comment by 13thdemarch** [comment]
> Thanks,
> Yes I'm using the AX motherboard, I'll check this out tomorrow.
> 
> Is there any other change you think I should do for thr AX board? 

No, just only USB mapping ports.
